FROM node:20-alpine AS build
WORKDIR /app

COPY src/main/resources/static/room-reservation-frontend/ ./

RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
