name: CD - Publish Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu (Checkout)
        uses: actions/checkout@v4

      - name: Konfiguracja Javy (Potrzebne do zbudowania .jar)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Budowanie pliku JAR
        run: mvn clean package -DskipTests

      - name: Logowanie do Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Konfiguracja Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- BACKEND ---
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: |
            kabox/room-reservation-backend:latest
            kabox/room-reservation-backend:${{ github.ref_name }}

      # --- FRONTEND ---
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: |
            kabox/room-reservation-frontend:latest
            kabox/room-reservation-frontend:${{ github.ref_name }}
